stages:
  - install
  - build
  - deploy

variables:
  APP_NAME: nodejs-devops-project
  IMAGE_NAME: hitesh008/nodejs-devops-project

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install
  image: node:22-alpine
  script:
    - npm ci

build_and_push_image:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - docker build -t $IMAGE_NAME:$CI_COMMIT_SHORT_SHA .
    - docker tag $IMAGE_NAME:$CI_COMMIT_SHORT_SHA $IMAGE_NAME:latest
    - docker push $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
    - docker push $IMAGE_NAME:latest

deploy_to_eks:
  stage: deploy
  image: alpine:3.20

  before_script:
    - apk add --no-cache curl unzip bash python3 py3-pip
    - pip3 install --break-system-packages awscli

    # Install kubectl
    - curl -LO https://dl.k8s.io/release/v1.33.13/bin/linux/amd64/kubectl
    - chmod +x kubectl
    - mv kubectl /usr/local/bin/

    # Install Helm
    - curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

  script:
    - aws eks update-kubeconfig --region $AWS_DEFAULT_REGION --name nodejs-devops

    - helm upgrade --install nodejs-devops ./helm/nodejs-devops \
        --set image.repository=$IMAGE_NAME \
        --set image.tag=$CI_COMMIT_SHORT_SHA