apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nodejs-devops.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "nodejs-devops.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "nodejs-devops.name" . }}
    spec:
      containers:
        - name: nodejs-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}